services:
  loki:
    user: root
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/config:/etc/loki
      - loki-storage:/loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  fluentd:
    image: my-fluentd-image
    command: ["fluentd", "-c", "/fluentd/etc/fluent.conf"]
    volumes:
      - ./fluentd/:/fluentd/etc
    ports:
      - "24224:24224"
    networks:
      - default

volumes:
  loki-storage:
  grafana-storage:

networks:
  default:
    driver: bridge
