version: '3.8'

services:
  loki:
    user: root
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./logging/loki/config:/etc/loki
      - loki-storage:/loki
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - default

  fluentd:
    image: my-fluentd-image
    command: ["fluentd", "-c", "/fluentd/etc/fluent.conf"]
    volumes:
      - ./logging/fluentd/:/fluentd/etc
    ports:
      - "24224:24224"
    networks:
      - default

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - default

  cadvisor:
    image: abeheshti127/cadvisor
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - default

  api:
    user: root
    image: mini_cloud_1-api
    # build:
    #   context: ./api
    #   dockerfile: Dockerfile
    ports:
      - "3500:3500"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./api:/app
      - /etc/nginx/sites-available:/etc/nginx/sites-available
      - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled
      - /etc/nginx/ssl:/etc/nginx/ssl
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/hosts:/etc/hosts
      - /run/systemd/system:/run/systemd/system
      # - /dev/minicloudVolume:/dev/minicloudVolume
      # - /dev/mapper:/dev/mapper
      # - /Volumes:/Volumes
      # - /var/lib/docker/volumes:/var/lib/docker/volumes
      # - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      # - /run:/run  
      # - /sys:/sys  
      # - /proc:/proc  
    networks:
      - default
    privileged: true
  mongo:
    image: mongo:latest
    volumes:
      - /var/lib/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - default
  nginx:
    image: nginx:latest 
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf  
      - /etc/nginx/sites-available:/etc/nginx/sites-available  
      - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled 
      - /etc/nginx/ssl:/etc/nginx/ssl
    networks:
      - default  

networks:
  default:
    driver: overlay
    attachable: true 

volumes:
  loki-storage:
  grafana-storage:
  mongo-data:
