version: '3.2'
services:
  loki:
    user: root
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./logging/loki/config:/etc/loki
      - loki-storage:/loki
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - default

  fluentd:
    image: my-fluentd-image
    command: ["fluentd", "-c", "/fluentd/etc/fluent.conf"]
    volumes:
      - ./logging/fluentd/:/fluentd/etc
    ports:
      - "24224:24224"
    networks:
      - default

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - default

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - default

volumes:
  loki-storage:
  grafana-storage:

networks:
  default:
    driver: bridge
